version: "2"
services:
  pgdb:
    image: 'postgres:12'
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data/pgdata
#    volumes:
#      - ${PG_MNT}:/var/lib/postgresql/data
    ports:
      - ${PG_OUTBOUND_PORT}:5432
